### ISSUE TITLE
No `push()` in the API after installing via npm

### ISSUE THREAD

**Issue by ikr** [rackt/history#122]
Tested with history v1.12 & 1.13

```
$ npm install history
$ babel-node
> const {createMemoryHistory} = require('history');
> createMemoryHistory().push('/foo');
repl:3
createMemoryHistory().push('/foo');
                      ^
TypeError: undefined is not a function
    at repl:3:23
    at Object.exports.runInThisContext (vm.js:74:17)
    at _eval (/usr/local/lib/node_modules/babel/lib/_babel-node.js:86:26)
    at REPLServer.replEval (/usr/local/lib/node_modules/babel/lib/_babel-node.js:169:14)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
> createMemoryHistory().pushState('/foo');
undefined
>
```

However, if I clone the project:

```
$ npm install
$ babel-node
> const {createMemoryHistory} = require('./lib/index');
'use strict'
> createMemoryHistory().push('/foo');
undefined
> createMemoryHistory().pushState('/foo');
undefined
>
```

Can there be a problem with the build script, so that an incomplete API gets published to the npm?

**Comment by knowbody** [comment]
nope, we added `push()` and `replace()` but it's on the master branch. Will be available after the next history release.

**Comment by ikr** [comment]
:) Got it, thanks. Sorry for bothering you.

**Comment by knowbody** [comment]
you're welcome. not bothering me :smile:
