### ISSUE TITLE
Calling createLocation statically is deprecated warning on server

### ISSUE THREAD

**Issue by esseb** [rackt/history#90]
I get this warning on my server now:

```
Warning: [history] Calling createLocation statically is deprecated; instead call the history.createLocation method - see docs/Location.md
```

This is how I use `createLocation` now:
```
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import createLocation from 'history/lib/createLocation';
[...]

module.exports = {
    viewApp: function (req, res) {
        var location = createLocation(req.url);
        [...]
```

If I try to do what https://github.com/rackt/history/blob/master/docs/Location.md says:
```
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { createHistory } from 'history';
[...]

module.exports = {
    viewApp: function (req, res) {
        var history = createHistory();
        var location = history.createLocation(req.url);
        [...]
```

I get this error:
```
 Error: Invariant Violation: Browser history needs a DOM
    at Object.invariant [as default] (/home/stein/repositories/livvin/node_modules/history/node_modules/invariant/invariant.js:44:15)
    at Object.createBrowserHistory [as createHistory] (/home/stein/repositories/livvin/node_modules/history/lib/createBrowserHistory.js:35:25)
```

What am I missing? Should this not work when run outside of a browser?

**Comment by taion** [comment]
Are you using this with React-Router's `match`? As of the the current release, you don't actually need to pass in a `Location` object: https://github.com/rackt/react-router/blob/v1.0.0-rc3/docs/guides/advanced/ServerRendering.md; you just need the URL.

**Comment by esseb** [comment]
Ah, that was it. Thanks, @taion
